cc_binary(
  name = "drill",
  srcs = ["build_letter.cc", "@ppp2code//file"],
)

cc_binary(
  name = "ex2",
  srcs = ["convert_mile_to_kilometer.cc", "@ppp2code//file"],
)

cc_binary(
  name = "ex3",
  srcs = ["invalid_decl.cc", "@ppp2code//file"],
)

cc_binary(
  name = "ex4",
  srcs = ["read_two_integers.cc", "@ppp2code//file"],
)

cc_binary(
  name = "ex5",
  srcs = ["read_two_doubles.cc", "@ppp2code//file"],
)

cc_binary(
  name = "ex6",
  srcs = ["sort_three_integers.cc", "@ppp2code//file"],
)

cc_binary(
  name = "ex7",
  srcs = ["sort_three_strings.cc", "@ppp2code//file"],
)

cc_binary(
  name = "ex8",
  srcs = ["check_parity.cc", "@ppp2code//file"],
)

cc_binary(
  name = "ex9",
  srcs = ["convert_string_to_number.cc", "@ppp2code//file"],
)

cc_binary(
  name = "ex10",
  srcs = ["calculator.cc", "@ppp2code//file"],
)

cc_binary(
  name = "ex11",
  srcs = ["read_coins.cc", "@ppp2code//file"],
)
