cc_binary(
  name = "drill",
  srcs = ["read_numbers.cc", "@ppp2code//file"],
)

cc_binary(
  name = "ex2",
  srcs = ["calculate_avg_and_med.cc", "@ppp2code//file"],
)

cc_binary(
  name = "ex3",
  srcs = ["read_distances.cc", "@ppp2code//file"],
)

cc_binary(
  name = "ex4",
  srcs = ["guess_number.cc", "@ppp2code//file"],
)

cc_binary(
  name = "ex5",
  srcs = ["calculator.cc", "@ppp2code//file"],
)

cc_binary(
  name = "ex6",
  srcs = ["convert_digits.cc", "@ppp2code//file"],
)

cc_binary(
  name = "ex7",
  srcs = ["calculator_with_digits.cc", "@ppp2code//file"],
)

cc_binary(
  name = "ex8",
  srcs = ["calculate_grains.cc", "@ppp2code//file"],
)

cc_binary(
  name = "ex10",
  srcs = ["rock_paper_scissors.cc", "@ppp2code//file"],
)

cc_binary(
  name = "ex14",
  srcs = ["prime_sieve.cc", "@ppp2code//file"],
)

cc_binary(
  name = "ex15",
  srcs = ["enum_primes.cc", "@ppp2code//file"],
)

cc_binary(
  name = "ex16",
  srcs = ["search_mode.cc", "@ppp2code//file"],
)

cc_binary(
  name = "ex17",
  srcs = ["search_mode_string.cc", "@ppp2code//file"],
)

cc_binary(
  name = "ex18",
  srcs = ["solve_quadratic_equation.cc", "@ppp2code//file"],
)

cc_binary(
  name = "ex19",
  srcs = ["read_scores.cc", "@ppp2code//file"],
)

cc_binary(
  name = "ex20",
  srcs = ["search_score.cc", "@ppp2code//file"],
)

cc_binary(
  name = "ex21",
  srcs = ["search_scorer.cc", "@ppp2code//file"],
)
