# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
  name = "drill",
  srcs = ["25_errors.cc", "@ppp2code//file"],
)

cc_binary(
  name = "ex2",
  srcs = ["c_to_k.cc", "@ppp2code//file"],
)

cc_binary(
  name = "ex5",
  srcs = ["celsius_and_kelvin.cc", "@ppp2code//file"],
)

cc_binary(
  name = "ex6",
  srcs = ["celsius_and_fahrenheit.cc", "@ppp2code//file"],
)

cc_binary(
  name = "ex7",
  srcs = ["solve_quadratic_equation.cc", "@ppp2code//file"],
)

cc_binary(
  name = "ex9",
  srcs = ["top_n_sum.cc", "@ppp2code//file"],
)

cc_binary(
  name = "ex10",
  srcs = ["top_n_sum_double.cc", "@ppp2code//file"],
)

cc_binary(
  name = "ex11",
  srcs = ["fibonacci.cc", "@ppp2code//file"],
)
